### ISSUE TITLE
New function to change the size of the SVG created

### ISSUE THREAD

**Issue by Sai-Prabhav** [anandology/csketch#2]
I wanted to change the max size of the SVG created by the sketch lib i was looking into the files in sketch folder to see how size assigned in the code. Found it was just writing hard coded text to the file. Made a variable size and added it in the write function and made another function to change the variable  and added it in the .h file to access it from our circle.c program

In the`sketch.h` file i just added `void set_size(int size);` (google said me to do it)

and  variable `size` and function `set_size` in sketch.c
```c
int size;
void set_size(int new_size){
    size=new_size;
}
```

After adding this you can change the size of svg in your code by calling `set_size(new_size)`

**Comment by anandology** [comment]
I think it would be good to have the `set_size` function take width and
height as arguments rather than just size. That will allow the sketch to be
rectangular as well instead of limiting it to be a square always.

Also, I think it may be good to call the function `set_sketch_size`.

What do you think?

**Comment by Sai-Prabhav** [comment]
Yes that totally do able and in fact the right way of doing it now I think of it. Using `set_sketch_size` will surely be less ambiguous, we can use that.

**Comment by Sai-Prabhav** [comment]
Update this in sketch.c
```c
int width = 600;
int height = 600;


void set_sketch_size(int new_width,int new_height){
    height=new_height;
    width=new_width;
}
```

edit `save_sketch` function to dynamically set height and width
```c
void save_sketch(char *filename)
{
    FILE *fp = fopen(filename, "w");

    fprintf(fp, "<?xml version='1.0' standalone='no'?>\n");
    fprintf(fp, "<svg version='1.1' viewBox='-%d -%d %d %d' width='%d' height='%d'  xmlns='http://www.w3.org/2000/svg'>\n", width / 2, height / 2, width, height, width, height);
    fprintf(fp, "<rect x='-%d' y='-%d' width='100%%' height='100%%' fill='white' />", width / 2, height / 2);
    fprintf(fp, "<g transform='scale(1, -1)'>\n");
    write_shapes(fp, shapes_list);
    fprintf(fp, "</g></svg>");
    fclose(fp);
}
```
Update the `sketch.h` to include the changed function
```c
void set_sketch_size(int new_width, int new_height);
```

**Comment by anandology** [comment]
I think it will be nice if you can send a pull request for these changes. 

For that you need to:

- fork this repository
- make a branch
- commit your changes 
- open a pull request

See this article to know about how to create a pull request.

https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github

**Comment by Sai-Prabhav** [comment]
Ok sir will do it after sometime. Thought of it at first but decided my
quality of code might not match the csketch standards.
Thank you 👍

**Comment by anandology** [comment]
The submission is very good. I thought it would be good for you to learn
how to send a PR and also it makes it easier to suggest any changes.
